# Generated by Django 4.0.3 on 2022-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalCareServerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='活动名')),
                ('place', models.CharField(max_length=64, verbose_name='地点')),
                ('start_time', models.DateField(verbose_name='活动开始时间')),
                ('lasting_time', models.CharField(max_length=64, verbose_name='持续时间')),
                ('score', models.CharField(max_length=64, verbose_name='积分')),
                ('activity_status', models.SmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (2, '已结束')], verbose_name='活动状态')),
            ],
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='api',
            field=models.CharField(max_length=255, verbose_name='api接口'),
        ),
    ]
